"""add MonitoredChat user_bot_id

Revision ID: 192fde4c1b7e
Revises: 1afdedb09062
Create Date: 2025-06-03 11:47:38.057160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "192fde4c1b7e"
down_revision: Union[str, None] = "1afdedb09062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("monitored_chats", sa.Column("user_bot_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        None,
        "monitored_chats",
        "user_bot",
        ["user_bot_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "monitored_chats", type_="foreignkey")
    op.drop_column("monitored_chats", "user_bot_id")
    # ### end Alembic commands ###
