"""create schemas 0.2v

Revision ID: 42c05850a0c4
Revises: 9f84708353e3
Create Date: 2025-05-25 16:21:19.319103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42c05850a0c4"
down_revision: Union[str, None] = "9f84708353e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts_tg_pars", "session_id")
    op.add_column("telegram_bots", sa.Column("session_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_bots", "session_id")
    op.add_column(
        "accounts_tg_pars",
        sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
