"""create schemas 0.5v

Revision ID: 6ae43e7df425
Revises: 61a78ed314f7
Create Date: 2025-05-26 14:09:16.869433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae43e7df425'
down_revision: Union[str, None] = '61a78ed314f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_tg_pars', sa.Column('_api_id', sa.String(), nullable=True))
    op.drop_column('accounts_tg_pars', 'api_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_tg_pars', sa.Column('api_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('accounts_tg_pars', '_api_id')
    # ### end Alembic commands ###
