"""create schemas 0.3v

Revision ID: a2682c924d47
Revises: 42c05850a0c4
Create Date: 2025-05-25 16:39:11.102059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2682c924d47'
down_revision: Union[str, None] = '42c05850a0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_tg_pars', sa.Column('name_account', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts_tg_pars', 'name_account')
    # ### end Alembic commands ###
